// <auto-generated />
using System;
using HomeMQ.MainContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomeMQ.MainContext.Migrations
{
    [DbContext(typeof(HomeMQMainContext))]
    [Migration("20210106203945_UpdateColumns")]
    partial class UpdateColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("HomeMQ.MainContext.LocationSQL", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Room")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("HomeMQ.MainContext.SensorSQL", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("SensorId");

                    b.HasIndex("LocationId");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("HomeMQ.MainContext.TemperatureReadingSQL", b =>
                {
                    b.Property<int>("ReadingId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("ReadingId");

                    b.HasIndex("SensorId");

                    b.ToTable("TemperatureReadings");
                });

            modelBuilder.Entity("HomeMQ.MainContext.SensorSQL", b =>
                {
                    b.HasOne("HomeMQ.MainContext.LocationSQL", "Location")
                        .WithMany("SensorSQLs")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("HomeMQ.MainContext.TemperatureReadingSQL", b =>
                {
                    b.HasOne("HomeMQ.MainContext.SensorSQL", "Sensor")
                        .WithMany("TemperatureReadingSQLs")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("HomeMQ.MainContext.LocationSQL", b =>
                {
                    b.Navigation("SensorSQLs");
                });

            modelBuilder.Entity("HomeMQ.MainContext.SensorSQL", b =>
                {
                    b.Navigation("TemperatureReadingSQLs");
                });
#pragma warning restore 612, 618
        }
    }
}
